apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "ytop-chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "ytop-chart.fullname" . }}-webhook-cert
  labels:
  {{- include "ytop-chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "ytop-chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-cluster-ytsaurus-tech-v1-chyt
  failurePolicy: Fail
  name: mchyt.kb.io
  rules:
  - apiGroups:
    - cluster.ytsaurus.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - chyts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "ytop-chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-cluster-ytsaurus-tech-v1-spyt
  failurePolicy: Fail
  name: mspyt.kb.io
  rules:
  - apiGroups:
    - cluster.ytsaurus.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - spyts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "ytop-chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-cluster-ytsaurus-tech-v1-ytsaurus
  failurePolicy: Fail
  name: mytsaurus.kb.io
  rules:
  - apiGroups:
    - cluster.ytsaurus.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ytsaurus
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "ytop-chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-pod-binding
  failurePolicy: Ignore
  name: yt-pod-rack.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods/binding
  sideEffects: None